### ISSUE TITLE
User story sprint-2 testen of nieuwe code accessible implementeren?

### ISSUE THREAD

**Issue by solideagency** [fdnd-task/all-human-accessible-website#1]
Niet iedereen heeft genoeg code om twee weken lang te testen. De code is vaak nog erg simpel. Plus voor de opdrachtgever is het ook fijn om op vrijdag niet alleen maar audits te zien. Wat denken jullie?

De aanpak bijvoorbeeld zo:
1. Fork en Clone deze leertaak
2. Kopieer de code van de user story waar je aan hebt gewerkt naar deze leertaak
3. Schrijf de user story waar jij aan gaat werken in de Readme van deze leertaak, dit is wat je gaat ontwerpen, maken en testen
4. Verwerk de feedback die je bij de Sprint Review van de vorige sprint hebt gekregen
5. Voer verschillende toegankelijkheid tests uit op de bestaande code en verbeter de problemen
6. Ga verder met uitwerken van de user story en gebruik daarbij de A11Y checklist 
7. Documenteer je proces a.h.v de development life cycle
8. En schrijf een goede readme

**Comment by KoopReynders** [comment]
Goed plan
