### ISSUE TITLE
Wat doen we met studenten die van user story willen wisselen?

### ISSUE THREAD

**Issue by solideagency** [fdnd-task/all-human-accessible-website#2]
Een aantal OBA studenten willen graag een nieuwe uitdaging en willen aan een nieuwe user story werken. Er worden bijvoorbeeld repo's samengevoegd en anderen gaan daar wel op door.

**Comment by KoopReynders** [comment]
Prima toch?

**Comment by ju5tu5** [comment]
Ja precies! Als ze willen switchen.. go go!
