### ISSUE TITLE
Twee checkboxen minder? Het is best veel

### ISSUE THREAD

**Issue by solideagency** [fdnd-task/all-human-accessible-website#3]
In de WCAG deel taak staan deze eigenlijk ook al. Zullen we deze twee checkboxen dan hier weghalen?

-  Je hebt interactive elements check gedaan en gevonden problemen verholpen
-  Je hebt headings and landmarks check gedaan en gevonden problemen verholpen

**Comment by KoopReynders** [comment]
Ik wilde eigenlijk precies dezelfde checks bij de criteria van de leertaak als wat studenten gaan doen in de deeltaak. In de deeltaak leren ze de checks te doen, daarna moeten ze dit 'altijd' doen voor hun opdrachten.

**Comment by ju5tu5** [comment]
Ik denk idd dat de tweede check bij de deeltaak samen deze lijst dekt. Maar dan mis ik nog: Je hebt een Lighthouse test gedaan op een bestaande website en de test is gedocumenteerd in de Wiki van deze deeltaak

**Comment by ju5tu5** [comment]
Zijn die 2 niet prima?

- Je hebt een Lighthouse test gedaan op een bestaande website en de test is gedocumenteerd in de Wiki van deze deeltaak
- Je hebt een een serie handmatige tests gedaan en gedocumenteerd in de wiki

**Comment by KoopReynders** [comment]
Top
